### ISSUE TITLE
Put it Online

### ISSUE THREAD

**Issue by AlissonSteffens** [noschang/ibfitajai#1]
We should use Heroku or NetLify, and put it on the line

**Comment by noschang** [comment]
Nice!

But first I need to make the site.
Right now it's just a Laravel Template.

Rsrsrsrsrrs

**Comment by AlissonSteffens** [comment]
Just do it!!
![m5mqx_s-200x150](https://cloud.githubusercontent.com/assets/6234230/26788560/f3ee7fd2-49e3-11e7-9099-028fd9c69ea0.gif)

**Comment by AlissonSteffens** [comment]
looks like a dead repo 😢

**Comment by noschang** [comment]
I'ts a dead Repo. I will erase it!
